name: Auto Deploy Bug Analytics App

on:
  push:
    branches:
      - main   # or change if your repo uses "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Rocky Linux Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          /home/dpd/deploy_bug_analytics.sh
