name: Daily Bug Digest Email

on:
  schedule:
    - cron: '0 1 * * *'  # Daily at 1:00 AM UTC
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 This is the critical fix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bug email notifier
        env: 
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python src/dashboard/bug_email_notifier.py

      - name: Commit updated database if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/bug_data.db
          git diff --cached --quiet || git commit -m "Update bug_data.db in workflow"

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
