name: Three Days Update

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    # 👇 Grant write permission to contents (needed for pushing commits)
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync with latest master
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [ "$BRANCH" = "$GITHUB_REF" ]; then
            echo "Unsupported ref $GITHUB_REF" >&2
            exit 1
          fi
          git fetch origin "$BRANCH"
          git rebase "origin/$BRANCH"
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python src/data_processing/run_pipeline.py

      - name: Commit data outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data/bug_data.db
          if git diff --cached --quiet; then
            echo "No data changes to commit"
          else
            git commit -m "Update data CSV files and database"
            git push origin HEAD:${{ github.ref }}
          fi

      - name: Upload data outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-data
          path: |
            data/*.csv
            data/bug_data.db
